from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

from .errors import WorkspaceError
from .frontmatter import read_record_data
from .storage import (
    ABSENT,
    RESOURCE_ID_RE,
    _git,
    artifact_file,
    atomic_write,
    digest,
    initialize_dirs,
    projection_file,
    qp_path,
    repository_root,
    resource_paths,
    validate_expected_digest,
    workspace_lock,
    workspace_path,
    workspace_root,
)

INDEX_NOTICE = "<!-- Generated by Akosile. Edit records or .qp/settings.json, not this file. -->"
LEGACY_ROOTS = ("plans", "architecture", "reports", "research", "triage", "findings", "state")


def read_settings(repo: Path) -> dict[str, Any]:
    path = qp_path(repo, "settings.json")
    if not path.exists():
        return {"exists": False, **resource_paths(repo, path)}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise WorkspaceError("INVALID_SETTINGS", "settings.json is malformed", error=str(error)) from error
    if not isinstance(value, dict):
        raise WorkspaceError("INVALID_SETTINGS", "settings.json must contain a JSON object")
    return {"exists": True, "value": value, "digest": digest(path), **resource_paths(repo, path)}


def write_settings(repo: Path, text: str, expected: str) -> dict[str, Any]:
    expected = validate_expected_digest(expected)
    try:
        value = json.loads(text)
    except json.JSONDecodeError as error:
        raise WorkspaceError("INVALID_SETTINGS", "Candidate settings are malformed", error=str(error)) from error
    if not isinstance(value, dict):
        raise WorkspaceError("INVALID_SETTINGS", "Candidate settings must be a JSON object")
    initialize_dirs(repo)
    path = qp_path(repo, "settings.json")
    with workspace_lock(repo, "settings"):
        current = read_settings(repo) if path.exists() else None
        if current and expected == ABSENT:
            raise WorkspaceError("SETTINGS_EXIST", "settings.json already exists")
        if current and current["digest"] != expected:
            raise WorkspaceError("STALE_WRITE", "settings.json changed since the caller's exact read")
        if not current and expected != ABSENT:
            raise WorkspaceError("SETTINGS_MISSING", "Expected settings.json does not exist")
        latest = digest(path) if path.exists() else None
        if latest != (current["digest"] if current else None):
            raise WorkspaceError("CONCURRENT_CHANGE", "settings.json changed during the write")
        atomic_write(path, text if text.endswith("\n") else text + "\n")
        written = read_settings(repo)
    return written


def scan_records(
    repo: Path,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]]]:
    rows: list[dict[str, Any]] = []
    invalid: list[dict[str, Any]] = []
    subjects: dict[tuple[str, str], list[str]] = {}
    root = qp_path(repo, "records")
    if not root.exists():
        return rows, invalid, []
    for path in sorted(root.glob("*/*/record.md")):
        try:
            data = read_record_data(repo, path)
            normalized = data["normalized"]
            ref = f"{normalized['owner']}/{path.parent.name}"
            view = projection_file(repo, ref)
            row = {
                **normalized,
                "updated_at": data["metadata"]["updated_at"],
                "record": workspace_path(repo, path).removeprefix(".qp/"),
                "view": workspace_path(repo, view).removeprefix(".qp/") if view.exists() else None,
            }
            rows.append(row)
            if normalized["subject"] is not None:
                subjects.setdefault((normalized["owner"], normalized["subject"]), []).append(
                    row["record"]
                )
        except WorkspaceError as error:
            invalid.append({"path": workspace_path(repo, path), **error.payload()})
    duplicates = [
        {"owner": owner, "subject": subject, "records": records}
        for (owner, subject), records in sorted(subjects.items())
        if len(records) > 1
    ]
    return rows, invalid, duplicates


def _cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def index_candidate(repo: Path) -> dict[str, Any]:
    rows, invalid, duplicates = scan_records(repo)
    missing_subjects = [row["record"] for row in rows if row["subject"] is None]
    lines = [
        INDEX_NOTICE,
        "",
        "# QP workspace records",
        "",
        "| Updated | Owner | Type | Title | Status | Record | View |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in sorted(rows, key=lambda item: item["instant"], reverse=True):
        view = f"[HTML]({row['view']})" if row["view"] else "—"
        lines.append(
            f"| {_cell(row['updated_at'])} | `{row['owner']}` | {row['record_type']} | "
            f"{_cell(row['title'])} | {_cell(row['status'])} | "
            f"[Record]({row['record']}) | {view} |"
        )
    if not rows:
        lines.append("| — | — | — | — | — | — | — |")
    if invalid:
        lines += ["", "## Invalid records", ""]
        lines += [
            f"- `{item['path']}` — `{item['code']}`: {item.get('message', '')}"
            for item in invalid
        ]
    if missing_subjects:
        lines += ["", "## Legacy records missing subject", ""]
        lines += [f"- `{path}`" for path in missing_subjects]
    if duplicates:
        lines += ["", "## Duplicate subjects", ""]
        for item in duplicates:
            records = ", ".join(f"`{path}`" for path in item["records"])
            lines.append(f"- `{item['owner']}` / `{item['subject']}` — {records}")
    return {
        "content": "\n".join(lines) + "\n",
        "records": len(rows),
        "invalid": invalid,
        "missing_subjects": missing_subjects,
        "duplicates": duplicates,
    }


def rebuild_index(repo: Path) -> dict[str, Any]:
    initialize_dirs(repo)
    path = qp_path(repo, "INDEX.md")
    with workspace_lock(repo, "index"):
        candidate = index_candidate(repo)
        atomic_write(path, candidate["content"])
    return {
        "records": candidate["records"],
        "invalid": candidate["invalid"],
        "missing_subjects": candidate["missing_subjects"],
        "duplicates": candidate["duplicates"],
        "digest": digest(path),
        **resource_paths(repo, path),
    }


def git_hygiene(repo: Path) -> str:
    root = repository_root(repo)
    try:
        result = _git(root, "check-ignore", "-q", "--", ".qp", check=False)
    except OSError:
        return "NOT_APPLICABLE"
    return "CURRENT" if result.returncode == 0 else "MISSING"


def ensure_git_exclude(repo: Path) -> str:
    root = repository_root(repo)
    try:
        _git(root, "rev-parse", "--is-inside-work-tree")
    except (OSError, subprocess.CalledProcessError):
        return "NOT_APPLICABLE"
    if git_hygiene(root) == "CURRENT":
        return "CURRENT"
    exclude = Path(_git(root, "rev-parse", "--git-path", "info/exclude").stdout.strip())
    if not exclude.is_absolute():
        exclude = root / exclude
    exclude.parent.mkdir(parents=True, exist_ok=True)
    with workspace_lock(repo, "git-exclude"):
        current = exclude.read_text(encoding="utf-8") if exclude.exists() else ""
        if ".qp/" not in current.splitlines() and ".qp" not in current.splitlines():
            with exclude.open("a", encoding="utf-8") as handle:
                if current and not current.endswith("\n"):
                    handle.write("\n")
                handle.write(".qp/\n")
    return git_hygiene(root)


def initialize(repo: Path) -> dict[str, Any]:
    root = initialize_dirs(repo)
    settings = qp_path(repo, "settings.json")
    with workspace_lock(repo, "settings"):
        if not settings.exists():
            atomic_write(settings, "{}\n")
            settings_state = "CREATED"
        else:
            try:
                read_settings(repo)
                settings_state = "PRESERVED"
            except WorkspaceError:
                settings_state = "INVALID_PRESERVED"
    return {
        "workspace": str(root),
        "workspace_path": workspace_path(repo, root),
        "settings_state": settings_state,
        "index": rebuild_index(repo),
        "git_hygiene": ensure_git_exclude(repo),
    }


def _raw_workspace_root(repo: Path) -> Path:
    return repository_root(repo) / ".qp"


def _safe_component_issue(repo: Path, root: Path, name: str) -> dict[str, Any] | None:
    raw = root / name
    if raw.is_symlink():
        return {"code": "SYMLINK_ESCAPE", "path": workspace_path(repo, raw)}
    return None


def doctor(repo: Path) -> dict[str, Any]:
    raw_root = _raw_workspace_root(repo)
    if raw_root.is_symlink():
        return {
            "status": "ISSUES_FOUND",
            "workspace": str(raw_root),
            "settings": None,
            "records": 0,
            "git_hygiene": git_hygiene(repo),
            "issues": [{"code": "SYMLINK_ESCAPE", "path": ".qp"}],
        }
    root = workspace_root(repo)
    if not root.exists():
        return {
            "status": "MISSING",
            "workspace": str(root),
            "issues": [{"code": "WORKSPACE_MISSING"}],
        }
    issues: list[dict[str, Any]] = []
    for component in ("records", "artifacts", ".locks"):
        issue = _safe_component_issue(repo, root, component)
        if issue:
            issues.append(issue)
    if issues:
        return {
            "status": "ISSUES_FOUND",
            "workspace": str(root),
            "settings": None,
            "records": 0,
            "git_hygiene": git_hygiene(repo),
            "issues": issues,
        }

    try:
        settings = read_settings(repo)
    except WorkspaceError as error:
        settings = {"error": error.payload()}
        issues.append(error.payload())
    candidate = index_candidate(repo)
    issues += candidate["invalid"]
    issues += [
        {"code": "MISSING_SUBJECT", "path": path}
        for path in candidate["missing_subjects"]
    ]
    issues += [{"code": "DUPLICATE_SUBJECT", **item} for item in candidate["duplicates"]]
    index = qp_path(repo, "INDEX.md")
    if not index.exists() or index.read_text(encoding="utf-8") != candidate["content"]:
        issues.append({"code": "INDEX_STALE_OR_MISSING", "path": workspace_path(repo, index)})

    records_root = qp_path(repo, "records")
    for bundle in records_root.glob("*/*") if records_root.exists() else ():
        if bundle.is_symlink():
            issues.append({"code": "SYMLINK_ESCAPE", "path": workspace_path(repo, bundle)})
        elif bundle.is_dir() and RESOURCE_ID_RE.fullmatch(bundle.name):
            legacy = bundle / "index.html"
            if legacy.exists():
                record_ref = f"{bundle.parent.name}/{bundle.name}"
                issues.append(
                    {
                        "code": "LEGACY_INDEX_HTML",
                        "path": workspace_path(repo, legacy),
                        "expected": workspace_path(repo, projection_file(repo, record_ref)),
                    }
                )

    artifacts = qp_path(repo, "artifacts")
    for bundle in artifacts.iterdir() if artifacts.exists() else ():
        if bundle.is_symlink():
            issues.append({"code": "SYMLINK_ESCAPE", "path": workspace_path(repo, bundle)})
        elif bundle.is_dir() and RESOURCE_ID_RE.fullmatch(bundle.name):
            legacy = bundle / "index.html"
            if legacy.exists():
                issues.append(
                    {
                        "code": "LEGACY_INDEX_HTML",
                        "path": workspace_path(repo, legacy),
                        "expected": workspace_path(repo, artifact_file(repo, bundle.name)),
                    }
                )
    for name in LEGACY_ROOTS:
        path = root / name
        if path.exists():
            issues.append({"code": "LEGACY_ROOT", "path": workspace_path(repo, path)})
    hygiene = git_hygiene(repo)
    if hygiene == "MISSING":
        issues.append({"code": "GIT_HYGIENE_MISSING"})
    return {
        "status": "HEALTHY" if not issues else "ISSUES_FOUND",
        "workspace": str(root),
        "settings": settings,
        "records": candidate["records"],
        "git_hygiene": hygiene,
        "issues": issues,
    }


def repair(repo: Path) -> dict[str, Any]:
    before = doctor(repo)
    if _raw_workspace_root(repo).is_symlink():
        return {
            "before": before,
            "changed": {"state": "BLOCKED", "reason": "SYMLINK_ESCAPE"},
            "after": before,
            "semantic_records_modified": False,
            "legacy_migration_performed": False,
        }
    changed = initialize(repo)
    return {
        "before": before,
        "changed": changed,
        "after": doctor(repo),
        "semantic_records_modified": False,
        "legacy_migration_performed": False,
    }
