#!/usr/bin/env python3
"""Rebuild `.qp/INDEX.md` deterministically from owner record frontmatter."""
from __future__ import annotations

import argparse
import json
import os
import re
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml
from filelock import FileLock, Timeout

INDEX_NOTICE = "<!-- Generated by Akosile. Edit records, not this file. -->"
OWNER_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
RECORD_ID_RE = re.compile(r"^\d{8}-(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)$")


class IndexBuildError(Exception):
    def __init__(self, code: str, message: str, **details: Any) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details

    def payload(self) -> dict[str, Any]:
        result: dict[str, Any] = {"code": self.code, "message": self.message}
        if self.details:
            result["details"] = self.details
        return result


class FrontmatterLoader(yaml.SafeLoader):
    pass


FrontmatterLoader.yaml_implicit_resolvers = {
    key: [(tag, pattern) for tag, pattern in rules if tag != "tag:yaml.org,2002:timestamp"]
    for key, rules in yaml.SafeLoader.yaml_implicit_resolvers.items()
}


def unique_mapping(
    loader: FrontmatterLoader, node: yaml.nodes.MappingNode, deep: bool = False
) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        if not isinstance(key, str) or key in result:
            raise yaml.constructor.ConstructorError(
                "while constructing frontmatter",
                node.start_mark,
                "frontmatter keys must be unique strings",
                key_node.start_mark,
            )
        result[key] = loader.construct_object(value_node, deep=deep)
    return result


FrontmatterLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, unique_mapping)


def split_frontmatter(text: str) -> dict[str, Any]:
    if not text.startswith("---\n"):
        raise IndexBuildError("INVALID_FRONTMATTER", "Record must start with YAML frontmatter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise IndexBuildError("INVALID_FRONTMATTER", "Record frontmatter is not terminated")
    try:
        metadata = yaml.load(text[4:end], Loader=FrontmatterLoader) or {}
    except yaml.YAMLError as error:
        raise IndexBuildError(
            "INVALID_FRONTMATTER",
            "Record frontmatter is not valid YAML",
            error=str(error),
        ) from error
    if not isinstance(metadata, dict):
        raise IndexBuildError("INVALID_FRONTMATTER", "Record frontmatter must be a mapping")
    return metadata


def required_string(metadata: dict[str, Any], key: str) -> str:
    value = metadata.get(key)
    if not isinstance(value, str) or not value.strip():
        raise IndexBuildError("INVALID_RECORD", f"{key} must be a non-empty string", field=key)
    return value


def parse_instant(value: Any) -> datetime:
    if not isinstance(value, str):
        raise IndexBuildError(
            "INVALID_UPDATED_AT", "updated_at must be an offset-aware ISO-8601 string"
        )
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError as error:
        raise IndexBuildError(
            "INVALID_UPDATED_AT", "updated_at must be an offset-aware ISO-8601 string"
        ) from error
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise IndexBuildError("INVALID_UPDATED_AT", "updated_at must include a UTC offset")
    return parsed.astimezone(timezone.utc)


def reject_symlink_path(workspace: Path, path: Path) -> None:
    try:
        relative = path.relative_to(workspace)
    except ValueError as error:
        raise IndexBuildError("PATH_ESCAPE", "Record is outside the workspace") from error
    current = workspace
    for part in relative.parts:
        current /= part
        if current.is_symlink():
            raise IndexBuildError("SYMLINK_PATH", "Record path cannot traverse symbolic links")


def inspect_record(workspace: Path, path: Path) -> dict[str, Any]:
    reject_symlink_path(workspace, path)
    metadata = split_frontmatter(path.read_text(encoding="utf-8"))
    owner = required_string(metadata, "owner")
    if not OWNER_RE.fullmatch(owner):
        raise IndexBuildError("INVALID_OWNER", "owner must be a canonical ASCII skill name")
    if owner != path.parent.parent.name:
        raise IndexBuildError(
            "OWNER_PATH_MISMATCH", "Frontmatter owner does not match the owner directory"
        )
    record_type = required_string(metadata, "record_type")
    title = required_string(metadata, "title")
    status = required_string(metadata, "status")
    updated_at = required_string(metadata, "updated_at")
    instant = parse_instant(updated_at)
    revision = metadata.get("revision")
    if isinstance(revision, bool) or not isinstance(revision, int) or revision < 1:
        raise IndexBuildError("INVALID_RECORD", "revision must be a positive integer", field="revision")
    match = RECORD_ID_RE.fullmatch(path.parent.name)
    if not match:
        raise IndexBuildError("INVALID_RECORD_ID", "Record directory must be <YYYYMMDD>-<stable-slug>")
    slug = match.group("slug")
    view = path.parent / f"{slug}.html"
    legacy_view = path.parent / "index.html"
    return {
        "updated_at": updated_at,
        "instant": instant,
        "owner": owner,
        "record_type": record_type,
        "title": title,
        "status": status,
        "record": path.relative_to(workspace).as_posix(),
        "view": (
            view.relative_to(workspace).as_posix()
            if view.is_file() and not view.is_symlink()
            else None
        ),
        "legacy_view": (
            legacy_view.relative_to(workspace).as_posix()
            if legacy_view.is_file() and not legacy_view.is_symlink()
            else None
        ),
        "expected_view": view.relative_to(workspace).as_posix(),
    }


def cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render(
    rows: list[dict[str, Any]],
    invalid: list[dict[str, Any]],
    legacy: list[dict[str, str]],
) -> str:
    lines = [
        INDEX_NOTICE,
        "",
        "# QP workspace records",
        "",
        "| Updated | Owner | Type | Title | Status | Record | View |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in sorted(rows, key=lambda item: item["instant"], reverse=True):
        view = f"[HTML]({row['view']})" if row["view"] else "—"
        lines.append(
            f"| {cell(row['updated_at'])} | `{cell(row['owner'])}` | {cell(row['record_type'])} | "
            f"{cell(row['title'])} | {cell(row['status'])} | [Record]({row['record']}) | {view} |"
        )
    if not rows:
        lines.append("| — | — | — | — | — | — | — |")
    if invalid:
        lines += ["", "## Invalid records", ""]
        for item in invalid:
            lines.append(f"- `{item['path']}` — `{item['code']}`: {item['message']}")
    if legacy:
        lines += ["", "## Legacy HTML entrypoints", ""]
        for item in legacy:
            lines.append(
                f"- `{item['path']}` — use `{item['expected']}` for the next owner-authorized projection"
            )
    return "\n".join(lines) + "\n"


def atomic_write(path: Path, text: str) -> None:
    if path.is_symlink():
        raise IndexBuildError("SYMLINK_INDEX", "INDEX.md cannot be a symbolic link")
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        if hasattr(os, "fchmod"):
            os.fchmod(descriptor, (path.stat().st_mode if path.exists() else 0o644) & 0o777)
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        if os.name != "nt":
            directory = os.open(path.parent, os.O_RDONLY)
            try:
                os.fsync(directory)
            finally:
                os.close(directory)
    finally:
        temporary.unlink(missing_ok=True)


def rebuild(workspace: Path, timeout: float = 30.0) -> dict[str, Any]:
    supplied = Path(os.path.abspath(workspace.expanduser()))
    if supplied.is_symlink():
        raise IndexBuildError("SYMLINK_WORKSPACE", "Workspace cannot be a symbolic link")
    if not supplied.exists() or not supplied.is_dir():
        raise IndexBuildError("WORKSPACE_MISSING", "Workspace must be an existing directory")
    workspace = supplied.resolve()
    records = workspace / "records"
    if records.is_symlink():
        raise IndexBuildError("SYMLINK_RECORDS", "records cannot be a symbolic link")

    index = workspace / "INDEX.md"
    lock_path = workspace / ".INDEX.md.lock"
    if lock_path.is_symlink():
        raise IndexBuildError("SYMLINK_LOCK", "Index lock cannot be a symbolic link")
    try:
        with FileLock(str(lock_path), timeout=timeout):
            rows: list[dict[str, Any]] = []
            invalid: list[dict[str, Any]] = []
            legacy: list[dict[str, str]] = []
            for path in sorted(records.glob("*/*/record.md")) if records.exists() else ():
                try:
                    row = inspect_record(workspace, path)
                    rows.append(row)
                    if row["legacy_view"]:
                        legacy.append(
                            {"path": row["legacy_view"], "expected": row["expected_view"]}
                        )
                except (IndexBuildError, UnicodeError, OSError) as error:
                    if isinstance(error, IndexBuildError):
                        payload = error.payload()
                        code, message = payload["code"], payload["message"]
                    else:
                        code, message = "READ_FAILED", str(error)
                    invalid.append(
                        {
                            "path": path.relative_to(workspace).as_posix(),
                            "code": code,
                            "message": message,
                        }
                    )
            content = render(rows, invalid, legacy)
            atomic_write(index, content)
    except Timeout as error:
        raise IndexBuildError("LOCK_TIMEOUT", "Timed out waiting for the index lock") from error
    except OSError as error:
        raise IndexBuildError(
            "INDEX_WRITE_FAILED", "Could not write INDEX.md", error=str(error)
        ) from error
    return {
        "workspace": str(workspace),
        "index": str(index),
        "records": len(rows),
        "invalid": invalid,
        "legacy_html": legacy,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, required=True)
    parser.add_argument("--timeout", type=float, default=30.0)
    args = parser.parse_args()
    try:
        result = rebuild(args.workspace, args.timeout)
    except IndexBuildError as error:
        print(json.dumps({"ok": False, "error": error.payload()}, ensure_ascii=False, indent=2))
        raise SystemExit(2) from error
    print(json.dumps({"ok": True, "result": result}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
