#!/usr/bin/env python3
"""Render canonical `.qp` owner records as Markdown on stdout."""
from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

NOTICE = "<!-- Generated by Akosile. Edit records, not this file. -->"
OWNER = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
SUBJECT = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


class Failure(Exception):
    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code, self.message = code, message


FRONTMATTER_KEY = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):(?:[ \t]*(.*))?$")
INTEGER = re.compile(r"^-?(?:0|[1-9][0-9]*)$")
SINGLE_QUOTED = re.compile(r"^'((?:[^']|'')*)'(?:[ \t]+#.*)?$")
COMMON_KEYS = {"owner", "record_type", "title", "updated_at", "revision", "status", "subject"}
UNSUPPORTED_SCALAR_PREFIXES = ("[", "{", "|", ">", "!", "&", "*")


def workspace_dir(path: Path) -> Path:
    raw = Path(os.path.abspath(path.expanduser()))
    if raw.is_symlink() or not raw.is_dir():
        raise Failure("WORKSPACE_MISSING", "Workspace must be an existing real directory")
    return raw.resolve()


def scalar(key: str, raw: str) -> Any:
    raw = raw.strip()
    if raw.startswith('"'):
        try:
            parsed, end = json.JSONDecoder().raw_decode(raw)
        except json.JSONDecodeError as error:
            raise Failure("INVALID_FRONTMATTER", f"Invalid quoted value for {key}") from error
        remainder = raw[end:]
        if remainder and not re.fullmatch(r"[ \t]+#.*", remainder):
            raise Failure("INVALID_FRONTMATTER", f"Unsupported content after {key}")
        return parsed
    if raw.startswith("'"):
        match = SINGLE_QUOTED.fullmatch(raw)
        if not match:
            raise Failure("INVALID_FRONTMATTER", f"Invalid quoted value for {key}")
        return match.group(1).replace("''", "'")

    raw = re.sub(r"[ \t]+#.*$", "", raw).rstrip()
    if raw.startswith(UNSUPPORTED_SCALAR_PREFIXES) or raw.startswith(("- ", "? ")):
        raise Failure("INVALID_FRONTMATTER", f"Unsupported scalar form for {key}")
    if INTEGER.fullmatch(raw):
        return int(raw)
    if raw.lower() in {"true", "false"}:
        return raw.lower() == "true"
    if raw.lower() in {"null", "~"}:
        return None
    return raw


def metadata(text: str) -> dict[str, Any]:
    if not text.startswith("---\n") or (end := text.find("\n---\n", 4)) < 0:
        raise Failure("INVALID_FRONTMATTER", "Record must contain YAML frontmatter")
    value: dict[str, Any] = {}
    seen: set[str] = set()
    for line in text[4:end].splitlines():
        if not line.strip() or line.lstrip().startswith("#") or line[:1].isspace():
            continue
        match = FRONTMATTER_KEY.fullmatch(line)
        if not match:
            raise Failure("INVALID_FRONTMATTER", f"Unsupported top-level frontmatter line: {line}")
        key, raw = match.group(1), match.group(2) or ""
        if key in seen:
            raise Failure("INVALID_FRONTMATTER", f"Duplicate frontmatter key: {key}")
        seen.add(key)
        if key in COMMON_KEYS:
            value[key] = scalar(key, raw)
    return value


def required(value: dict[str, Any], key: str) -> str:
    result = value.get(key)
    if not isinstance(result, str) or not result.strip():
        raise Failure("INVALID_RECORD", f"{key} must be a non-empty string")
    return result.strip()


def instant(value: str) -> datetime:
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError as error:
        raise Failure("INVALID_UPDATED_AT", "updated_at must be offset-aware ISO-8601") from error
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise Failure("INVALID_UPDATED_AT", "updated_at must include a UTC offset")
    return parsed.astimezone(timezone.utc)


def inspect(workspace: Path, path: Path) -> dict[str, Any]:
    raw = Path(os.path.abspath(path))
    if raw.is_symlink() or raw.resolve() != raw:
        raise Failure("SYMLINK_PATH", "Record path cannot traverse symbolic links")
    value = metadata(raw.read_text(encoding="utf-8"))
    owner = required(value, "owner")
    if not OWNER.fullmatch(owner):
        raise Failure("INVALID_OWNER", "owner must be a canonical ASCII skill name")
    if owner != raw.parent.parent.name:
        raise Failure("OWNER_PATH_MISMATCH", "owner does not match its directory")
    subject = raw.parent.name
    if not SUBJECT.fullmatch(subject):
        raise Failure("INVALID_RECORD_ID", "record directory must be a stable ASCII subject")
    declared_subject = value.get("subject")
    if declared_subject is not None and declared_subject != subject:
        raise Failure("SUBJECT_PATH_MISMATCH", "subject does not match its directory")
    revision = value.get("revision")
    if isinstance(revision, bool) or not isinstance(revision, int) or revision < 1:
        raise Failure("INVALID_RECORD", "revision must be a positive integer")
    updated_at = required(value, "updated_at")
    view = raw.parent / "index.html"
    return {
        "instant": instant(updated_at),
        "updated_at": updated_at,
        "owner": owner,
        "record_type": required(value, "record_type"),
        "title": required(value, "title"),
        "status": required(value, "status"),
        "record": raw.relative_to(workspace).as_posix(),
        "view": view.relative_to(workspace).as_posix() if view.is_file() and not view.is_symlink() else None,
    }


def literal(value: Any) -> str:
    text = " ".join(str(value).replace("\r", "\n").splitlines())
    text = html.escape(text, quote=False)
    for char in ("\\", "`", "*", "_", "[", "]", "<", ">", "|"):
        text = text.replace(char, "\\" + char)
    return text


def render(rows: list[dict[str, Any]], invalid: list[dict[str, str]]) -> str:
    lines = [NOTICE, "", "# QP workspace records", "", "| Updated | Owner | Type | Title | Status | Record | View |", "|---|---|---|---|---|---|---|"]
    for row in sorted(rows, key=lambda item: item["instant"], reverse=True):
        view = f"[HTML]({row['view']})" if row["view"] else "—"
        lines.append(
            f"| {literal(row['updated_at'])} | `{literal(row['owner'])}` | {literal(row['record_type'])} | "
            f"{literal(row['title'])} | {literal(row['status'])} | [Record]({row['record']}) | {view} |"
        )
    if not rows:
        lines.append("| — | — | — | — | — | — | — |")
    if invalid:
        lines += ["", "## Invalid records", ""]
        for item in invalid:
            lines.append(f"- `{literal(item['path'])}` — `{literal(item['code'])}`: {literal(item['message'])}")
    return "\n".join(lines) + "\n"


def build(workspace: Path) -> str:
    workspace = workspace_dir(workspace)
    records = workspace / "records"
    if records.is_symlink():
        raise Failure("SYMLINK_RECORDS", "records cannot be a symbolic link")
    if records.exists() and not records.is_dir():
        raise Failure("INVALID_RECORDS", "records must be a directory")
    rows: list[dict[str, Any]] = []
    invalid: list[dict[str, str]] = []
    for path in sorted(records.glob("*/*/record.md")) if records.exists() else ():
        try:
            rows.append(inspect(workspace, path))
        except (Failure, UnicodeError, OSError) as error:
            invalid.append({
                "path": path.relative_to(workspace).as_posix(),
                "code": error.code if isinstance(error, Failure) else "READ_FAILED",
                "message": error.message if isinstance(error, Failure) else str(error),
            })
    return render(rows, invalid)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("workspace", type=Path)
    args = parser.parse_args()
    try:
        sys.stdout.write(build(args.workspace))
    except (Failure, OSError) as error:
        code = error.code if isinstance(error, Failure) else "READ_FAILED"
        message = error.message if isinstance(error, Failure) else str(error)
        print(f"{code}: {message}", file=sys.stderr)
        raise SystemExit(2) from error


if __name__ == "__main__":
    main()
