#!/usr/bin/env python3
"""Render one `.qp/INDEX.md` candidate from owner record frontmatter."""
from __future__ import annotations

import argparse
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

NOTICE = "<!-- Generated by Akosile. Edit records, not this file. -->"
OWNER = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
RECORD_ID = re.compile(r"^\d{8}-[a-z0-9]+(?:-[a-z0-9]+)*$")


class Failure(Exception):
    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code, self.message = code, message


class Loader(yaml.SafeLoader):
    pass


Loader.yaml_implicit_resolvers = {
    key: [(tag, pattern) for tag, pattern in rules if tag != "tag:yaml.org,2002:timestamp"]
    for key, rules in yaml.SafeLoader.yaml_implicit_resolvers.items()
}


def unique_mapping(loader: Loader, node: yaml.nodes.MappingNode, deep: bool = False) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        if not isinstance(key, str) or key in result:
            raise yaml.constructor.ConstructorError(
                "frontmatter", node.start_mark, "keys must be unique strings", key_node.start_mark
            )
        result[key] = loader.construct_object(value_node, deep=deep)
    return result


Loader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, unique_mapping)


def absolute(path: Path) -> Path:
    return Path(os.path.abspath(path.expanduser()))


def directory(path: Path, code: str, *, reject_symlink: bool = False) -> Path:
    raw = absolute(path)
    if not raw.is_dir() or (reject_symlink and raw.is_symlink()):
        raise Failure(code, "Path must be an existing directory")
    return raw.resolve()


def metadata(text: str) -> dict[str, Any]:
    if not text.startswith("---\n") or (end := text.find("\n---\n", 4)) < 0:
        raise Failure("INVALID_FRONTMATTER", "Record must contain YAML frontmatter")
    try:
        value = yaml.load(text[4:end], Loader=Loader) or {}
    except yaml.YAMLError as error:
        raise Failure("INVALID_FRONTMATTER", str(error)) from error
    if not isinstance(value, dict):
        raise Failure("INVALID_FRONTMATTER", "Frontmatter must be a mapping")
    return value


def required(value: dict[str, Any], key: str) -> str:
    result = value.get(key)
    if not isinstance(result, str) or not result.strip():
        raise Failure("INVALID_RECORD", f"{key} must be a non-empty string")
    return result


def instant(value: str) -> datetime:
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError as error:
        raise Failure("INVALID_UPDATED_AT", "updated_at must be offset-aware ISO-8601") from error
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise Failure("INVALID_UPDATED_AT", "updated_at must include a UTC offset")
    return parsed.astimezone(timezone.utc)


def inspect(workspace: Path, path: Path) -> dict[str, Any]:
    raw = absolute(path)
    if raw.is_symlink() or raw.resolve() != raw:
        raise Failure("SYMLINK_PATH", "Record path cannot traverse symbolic links")
    value = metadata(raw.read_text(encoding="utf-8"))
    owner = required(value, "owner")
    if not OWNER.fullmatch(owner):
        raise Failure("INVALID_OWNER", "owner must be a canonical ASCII skill name")
    if owner != raw.parent.parent.name:
        raise Failure("OWNER_PATH_MISMATCH", "owner does not match its directory")
    if not RECORD_ID.fullmatch(raw.parent.name):
        raise Failure("INVALID_RECORD_ID", "record directory must be <YYYYMMDD>-<stable-slug>")
    revision = value.get("revision")
    if isinstance(revision, bool) or not isinstance(revision, int) or revision < 1:
        raise Failure("INVALID_RECORD", "revision must be a positive integer")
    updated_at = required(value, "updated_at")
    view = raw.parent / "index.html"
    return {
        "instant": instant(updated_at),
        "updated_at": updated_at,
        "owner": owner,
        "record_type": required(value, "record_type"),
        "title": required(value, "title"),
        "status": required(value, "status"),
        "record": raw.relative_to(workspace).as_posix(),
        "view": view.relative_to(workspace).as_posix() if view.is_file() and not view.is_symlink() else None,
    }


def cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render(rows: list[dict[str, Any]], invalid: list[dict[str, str]]) -> str:
    lines = [NOTICE, "", "# QP workspace records", "", "| Updated | Owner | Type | Title | Status | Record | View |", "|---|---|---|---|---|---|---|"]
    for row in sorted(rows, key=lambda item: item["instant"], reverse=True):
        view = f"[HTML]({row['view']})" if row["view"] else "—"
        lines.append(f"| {cell(row['updated_at'])} | `{cell(row['owner'])}` | {cell(row['record_type'])} | {cell(row['title'])} | {cell(row['status'])} | [Record]({row['record']}) | {view} |")
    if not rows:
        lines.append("| — | — | — | — | — | — | — |")
    if invalid:
        lines += ["", "## Invalid records", ""] + [f"- `{item['path']}` — `{item['code']}`: {item['message']}" for item in invalid]
    return "\n".join(lines) + "\n"


def build(workspace: Path, output: Path) -> dict[str, Any]:
    workspace = directory(workspace, "WORKSPACE_MISSING", reject_symlink=True)
    records = workspace / "records"
    if records.is_symlink():
        raise Failure("SYMLINK_RECORDS", "records cannot be a symbolic link")
    if records.exists() and not records.is_dir():
        raise Failure("INVALID_RECORDS", "records must be a directory")
    rows: list[dict[str, Any]] = []
    invalid: list[dict[str, str]] = []
    for path in sorted(records.glob("*/*/record.md")) if records.exists() else ():
        try:
            rows.append(inspect(workspace, path))
        except (Failure, UnicodeError, OSError) as error:
            invalid.append({"path": path.relative_to(workspace).as_posix(), "code": error.code if isinstance(error, Failure) else "READ_FAILED", "message": error.message if isinstance(error, Failure) else str(error)})
    raw = absolute(output)
    parent = directory(raw.parent, "OUTPUT_PARENT_MISSING")
    if raw.is_symlink():
        raise Failure("SYMLINK_OUTPUT", "output cannot be a symbolic link")
    output = parent / raw.name
    try:
        output.relative_to(workspace)
    except ValueError:
        pass
    else:
        raise Failure("OUTPUT_INSIDE_WORKSPACE", "output must be outside the workspace")
    output.write_text(render(rows, invalid), encoding="utf-8", newline="\n")
    return {"workspace": str(workspace), "output": str(output), "records": len(rows), "invalid": invalid}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        result = build(args.workspace, args.output)
    except (Failure, OSError) as error:
        payload = {"code": error.code if isinstance(error, Failure) else "WRITE_FAILED", "message": error.message if isinstance(error, Failure) else str(error)}
        print(json.dumps({"ok": False, "error": payload}, indent=2, ensure_ascii=False))
        raise SystemExit(2) from error
    print(json.dumps({"ok": True, "result": result}, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
