#!/usr/bin/env python3
"""Small deterministic helpers for a repository-local QP workspace."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

OWNER_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
RECORD_ID_RE = re.compile(r"^\d{8}-[a-z0-9]+(?:-[a-z0-9]+)*(?:-\d+)?$")
INDEX_NOTICE = "<!-- Generated by Akosile. Edit records or .qp/settings.json, not this file. -->"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def repository_root(repo: Path) -> Path:
    """Resolve a path inside a Git repository to its worktree root."""
    resolved = repo.resolve()
    try:
        result = subprocess.run(
            ["git", "-C", str(resolved), "rev-parse", "--show-toplevel"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return resolved
    return Path(result.stdout.strip()).resolve()


def workspace_root(repo: Path) -> Path:
    """Resolve the canonical v0 workspace root. Keep root mechanics here, not in semantic skills."""
    return repository_root(repo) / ".qp"


def workspace_path(repo: Path, path: Path) -> str:
    """Return the stable repository-relative path used for user/project references."""
    return str(path.resolve(strict=False).relative_to(repository_root(repo)))


def resource_paths(repo: Path, path: Path) -> dict[str, str]:
    resolved = path.resolve(strict=False)
    return {"absolute_path": str(resolved), "workspace_path": workspace_path(repo, resolved)}


def ensure_inside(root: Path, path: Path) -> Path:
    root = root.resolve()
    target = path.resolve(strict=False)
    if target != root and root not in target.parents:
        raise ValueError(f"target escapes workspace: {path}")
    return target


def safe_owner(value: str) -> str:
    if not OWNER_RE.fullmatch(value):
        raise ValueError(f"invalid owner: {value!r}")
    return value


def safe_slug(value: str) -> str:
    if not SLUG_RE.fullmatch(value):
        raise ValueError(f"invalid slug: {value!r}")
    return value


def parse_updated_at(value: str) -> datetime:
    """Parse a record timestamp and normalize it to a comparable UTC instant."""
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError as error:
        raise ValueError("updated_at must be an offset-aware ISO-8601 timestamp") from error
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise ValueError("updated_at must be an offset-aware ISO-8601 timestamp")
    return parsed.astimezone(timezone.utc)


def atomic_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


def frontmatter_text(text: str) -> dict[str, str]:
    if not text.startswith("---\n"):
        raise ValueError("missing frontmatter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError("unterminated frontmatter")
    result: dict[str, str] = {}
    for raw in text[4:end].splitlines():
        if not raw or raw.startswith((" ", "\t")) or ":" not in raw:
            continue
        key, value = raw.split(":", 1)
        result[key.strip()] = value.strip().strip('"').strip("'")
    return result


def frontmatter(path: Path) -> dict[str, str]:
    return frontmatter_text(path.read_text(encoding="utf-8"))


def ensure_git_exclude(repo: Path) -> str:
    repo = repository_root(repo)
    try:
        ignored = subprocess.run(
            ["git", "-C", str(repo), "check-ignore", "-q", ".qp"],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        if ignored.returncode == 0:
            return "CURRENT"
        proc = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--git-path", "info/exclude"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return "NOT_APPLICABLE"

    exclude = Path(proc.stdout.strip())
    if not exclude.is_absolute():
        exclude = (repo / exclude).resolve()
    current = exclude.read_text(encoding="utf-8") if exclude.exists() else ""
    exclude.parent.mkdir(parents=True, exist_ok=True)
    with exclude.open("a", encoding="utf-8") as handle:
        if current and not current.endswith("\n"):
            handle.write("\n")
        handle.write(".qp/\n")
    return "CURRENT"


def init_workspace(repo: Path) -> dict[str, Any]:
    root = workspace_root(repo)
    (root / "records").mkdir(parents=True, exist_ok=True)
    (root / "artifacts").mkdir(parents=True, exist_ok=True)
    settings = root / "settings.json"
    if not settings.exists():
        atomic_text(settings, "{}\n")
    return {
        "workspace": str(root),
        "workspace_path": workspace_path(repo, root),
        "settings": str(settings),
        "index": rebuild_index(repo),
        "git_hygiene": ensure_git_exclude(repo),
    }


def allocate_id(parent: Path, slug: str) -> str:
    base = f"{datetime.now().astimezone():%Y%m%d}-{safe_slug(slug)}"
    record_id = base
    suffix = 2
    while (parent / record_id).exists():
        record_id = f"{base}-{suffix}"
        suffix += 1
    return record_id


def record_bundles(repo: Path, owner: str) -> list[Path]:
    parent = workspace_root(repo) / "records" / safe_owner(owner)
    if not parent.exists():
        return []
    return sorted(path for path in parent.iterdir() if path.is_dir() and (path / "record.md").exists())


def resolve_record(
    repo: Path,
    owner: str,
    slug: str,
    *,
    candidate: str | None = None,
    create: bool = False,
) -> dict[str, Any]:
    owner = safe_owner(owner)
    slug = safe_slug(slug)
    root = workspace_root(repo)
    owner_root = ensure_inside(root, root / "records" / owner)
    owner_root.mkdir(parents=True, exist_ok=True)

    if candidate:
        matches = []
        for bundle in record_bundles(repo, owner):
            try:
                if frontmatter(bundle / "record.md").get("candidate") == candidate:
                    matches.append(bundle)
            except ValueError:
                continue
        if len(matches) == 1:
            bundle = matches[0]
            return {"record_ref": f"{owner}/{bundle.name}", "bundle": str(bundle), "existing": True, **resource_paths(repo, bundle)}
        if len(matches) > 1:
            raise ValueError(f"multiple records share candidate {candidate!r}")

    pattern = re.compile(rf"^\d{{8}}-{re.escape(slug)}(?:-\d+)?$")
    matches = [path for path in record_bundles(repo, owner) if pattern.fullmatch(path.name)]
    if len(matches) == 1:
        bundle = matches[0]
        return {"record_ref": f"{owner}/{bundle.name}", "bundle": str(bundle), "existing": True, **resource_paths(repo, bundle)}
    if len(matches) > 1:
        raise ValueError(f"multiple records match owner={owner} slug={slug}")
    if not create:
        return {"record_ref": None, "bundle": None, "existing": False}

    record_id = allocate_id(owner_root, slug)
    bundle = ensure_inside(root, owner_root / record_id)
    bundle.mkdir()
    return {"record_ref": f"{owner}/{record_id}", "bundle": str(bundle), "existing": False, **resource_paths(repo, bundle)}


def resolve_artifact(repo: Path, slug: str, *, create: bool = False) -> dict[str, Any]:
    slug = safe_slug(slug)
    root = workspace_root(repo)
    parent = ensure_inside(root, root / "artifacts")
    parent.mkdir(parents=True, exist_ok=True)
    pattern = re.compile(rf"^\d{{8}}-{re.escape(slug)}(?:-\d+)?$")
    matches = [path for path in parent.iterdir() if path.is_dir() and pattern.fullmatch(path.name)]
    if len(matches) == 1:
        bundle = matches[0]
        html = bundle / "index.html"
        return {"artifact_id": bundle.name, "bundle": str(bundle), "html": str(html), "existing": True, **resource_paths(repo, html)}
    if len(matches) > 1:
        raise ValueError(f"multiple artifacts match slug={slug}")
    if not create:
        return {"artifact_id": None, "bundle": None, "html": None, "existing": False}
    artifact_id = allocate_id(parent, slug)
    bundle = ensure_inside(root, parent / artifact_id)
    bundle.mkdir()
    html = bundle / "index.html"
    return {"artifact_id": artifact_id, "bundle": str(bundle), "html": str(html), "existing": False, **resource_paths(repo, html)}


def validate_record_text(repo: Path, logical_path: Path, text: str) -> dict[str, Any]:
    errors: list[str] = []
    try:
        meta = frontmatter_text(text)
    except ValueError as exc:
        return {"valid": False, "errors": [str(exc)], "metadata": {}}

    required = ["owner", "record_type", "title", "updated_at", "revision", "status"]
    missing = [key for key in required if not meta.get(key)]
    if missing:
        errors.append(f"missing fields: {', '.join(missing)}")

    owner = meta.get("owner", "")
    record_id = logical_path.parent.name
    if owner and not OWNER_RE.fullmatch(owner):
        errors.append("invalid owner")
    if not RECORD_ID_RE.fullmatch(record_id):
        errors.append("invalid record directory")
    if owner:
        expected = workspace_root(repo) / "records" / owner / record_id / "record.md"
        if logical_path.resolve(strict=False) != expected.resolve(strict=False):
            errors.append(f"path must be {expected}")
    if meta.get("updated_at"):
        try:
            parse_updated_at(meta["updated_at"])
        except ValueError as error:
            errors.append(str(error))
    try:
        if int(meta.get("revision", "0")) < 1:
            errors.append("revision must be >= 1")
    except ValueError:
        errors.append("revision must be integer")
    return {"valid": not errors, "errors": errors, "metadata": meta}


def validate_record(repo: Path, path: Path) -> dict[str, Any]:
    path = ensure_inside(workspace_root(repo), path)
    result = validate_record_text(repo, path, path.read_text(encoding="utf-8"))
    result["digest"] = digest(path)
    return result


def scan_records(repo: Path) -> tuple[list[dict[str, str | None]], list[dict[str, Any]]]:
    root = workspace_root(repo)
    rows: list[dict[str, str | None]] = []
    invalid: list[dict[str, Any]] = []
    records = root / "records"
    if not records.exists():
        return rows, invalid
    for path in sorted(records.glob("*/*/record.md")):
        result = validate_record(repo, path)
        if not result["valid"]:
            invalid.append({"record": str(path.relative_to(root)), "errors": result["errors"]})
            continue
        meta = result["metadata"]
        view = path.parent / "index.html"
        rows.append({
            "updated_at": meta["updated_at"],
            "owner": meta["owner"],
            "record_type": meta["record_type"],
            "title": meta["title"],
            "status": meta["status"],
            "record": str(path.relative_to(root)),
            "view": str(view.relative_to(root)) if view.exists() else None,
        })
    return rows, invalid


def cell(value: str | None) -> str:
    return (value or "").replace("|", "\\|").replace("\n", " ")


def render_index(rows: list[dict[str, str | None]], invalid: list[dict[str, Any]]) -> str:
    lines = [
        INDEX_NOTICE,
        "",
        "# QP workspace records",
        "",
        "| Updated | Owner | Type | Title | Status | Record | View |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in sorted(rows, key=lambda item: parse_updated_at(item["updated_at"] or ""), reverse=True):
        view = f"[HTML]({row['view']})" if row["view"] else "—"
        lines.append(
            f"| {cell(row['updated_at'])} | `{cell(row['owner'])}` | {cell(row['record_type'])} | "
            f"{cell(row['title'])} | {cell(row['status'])} | [Record]({row['record']}) | {view} |"
        )
    if not rows:
        lines.append("| — | — | — | — | — | — | — |")
    if invalid:
        lines += ["", "## Invalid records", ""]
        for item in invalid:
            lines.append(f"- `{item['record']}`: {'; '.join(item['errors'])}")
    return "\n".join(lines) + "\n"


def rebuild_index(repo: Path) -> dict[str, Any]:
    root = workspace_root(repo)
    root.mkdir(parents=True, exist_ok=True)
    rows, invalid = scan_records(repo)
    index = root / "INDEX.md"
    atomic_text(index, render_index(rows, invalid))
    return {"path": str(index), "workspace_path": workspace_path(repo, index), "records": len(rows), "invalid": invalid}


def write_record(repo: Path, target: Path, candidate: Path, expected_digest: str | None) -> dict[str, Any]:
    root = workspace_root(repo)
    target = ensure_inside(root, target)
    target.parent.mkdir(parents=True, exist_ok=True)
    current_revision = 0
    current_digest: str | None = None
    if target.exists():
        current = validate_record(repo, target)
        if not current["valid"]:
            raise ValueError(f"current record invalid: {current['errors']}")
        if expected_digest is None:
            raise ValueError("expected digest is required for an existing record")
        current_revision = int(current["metadata"]["revision"])
        current_digest = current["digest"]
        if expected_digest != current_digest:
            raise ValueError("stale digest")
    elif expected_digest is not None:
        raise ValueError("record does not exist")

    candidate_text = candidate.read_text(encoding="utf-8")
    check = validate_record_text(repo, target, candidate_text)
    if not check["valid"]:
        raise ValueError(f"invalid candidate record: {check['errors']}")
    revision = int(check["metadata"]["revision"])
    if revision != current_revision + 1:
        raise ValueError(f"candidate revision must be {current_revision + 1}, got {revision}")

    if target.exists() and digest(target) != current_digest:
        raise ValueError("record changed concurrently")
    atomic_text(target, candidate_text)
    result = validate_record(repo, target)
    if not result["valid"]:
        raise ValueError(f"post-write validation failed: {result['errors']}")
    return {"record": str(target), "revision": revision, "digest": result["digest"], "index": rebuild_index(repo), **resource_paths(repo, target)}


def write_settings(repo: Path, candidate: Path, expected_digest: str | None) -> dict[str, Any]:
    root = workspace_root(repo)
    target = ensure_inside(root, root / "settings.json")
    raw = candidate.read_text(encoding="utf-8")
    data = json.loads(raw)
    if not isinstance(data, dict):
        raise ValueError("settings must be a JSON object")
    current_digest = digest(target) if target.exists() else None
    if target.exists() and expected_digest is None:
        raise ValueError("expected digest is required for existing settings")
    if expected_digest != current_digest:
        raise ValueError("stale settings digest")
    prewrite_digest = digest(target) if target.exists() else None
    if prewrite_digest != current_digest:
        raise ValueError("settings changed concurrently")
    atomic_text(target, raw if raw.endswith("\n") else raw + "\n")
    return {"settings": str(target), "digest": digest(target), **resource_paths(repo, target)}


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(description=__doc__)
    sub = root.add_subparsers(dest="command", required=True)

    def repo_arg(command: argparse.ArgumentParser) -> None:
        command.add_argument("--repo", type=Path, default=Path.cwd())

    init = sub.add_parser("init")
    repo_arg(init)

    resolve = sub.add_parser("resolve-record")
    repo_arg(resolve)
    resolve.add_argument("--owner", required=True)
    resolve.add_argument("--slug", required=True)
    resolve.add_argument("--candidate")
    resolve.add_argument("--create", action="store_true")

    artifact = sub.add_parser("resolve-artifact")
    repo_arg(artifact)
    artifact.add_argument("--slug", required=True)
    artifact.add_argument("--create", action="store_true")

    write = sub.add_parser("write-record")
    repo_arg(write)
    write.add_argument("--target", type=Path, required=True)
    write.add_argument("--candidate", type=Path, required=True)
    write.add_argument("--expected-digest")

    settings = sub.add_parser("write-settings")
    repo_arg(settings)
    settings.add_argument("--candidate", type=Path, required=True)
    settings.add_argument("--expected-digest")

    index = sub.add_parser("index")
    repo_arg(index)
    return root


def main() -> None:
    args = parser().parse_args()
    if args.command == "init":
        result = init_workspace(args.repo)
    elif args.command == "resolve-record":
        result = resolve_record(args.repo, args.owner, args.slug, candidate=args.candidate, create=args.create)
    elif args.command == "resolve-artifact":
        result = resolve_artifact(args.repo, args.slug, create=args.create)
    elif args.command == "write-record":
        result = write_record(args.repo, args.target, args.candidate, args.expected_digest)
    elif args.command == "write-settings":
        result = write_settings(args.repo, args.candidate, args.expected_digest)
    else:
        result = rebuild_index(args.repo)
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
