name: Release

on:
  push:
    tags:
      - 'v*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
